// <auto-generated />
namespace SNAS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _as : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_as));
        
        string IMigrationMetadata.Id
        {
            get { return "201608050919358_as"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
